version: "3.9"
services:
  db:
    image: postgres:16
    container_name: tasklyhr_db
    environment:
      POSTGRES_USER: taskly
      POSTGRES_PASSWORD: taskly
      POSTGRES_DB: taskly_hr
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskly -d taskly_hr"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  pgdata:
